import os
import re
from PIL import Image as PILImage
from agno.agent import Agent
from agno.models.google import Gemini
from agno.media import Image as AgnoImage
import streamlit as st
from gtts import gTTS
import base64

# ══════════════════════════════════════════════════════════════
#  CONFIGURATION
# ══════════════════════════════════════════════════════════════
GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY", "YOUR_GOOGLE_API_KEY_HERE")
os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY

if not GOOGLE_API_KEY or GOOGLE_API_KEY == "YOUR_GOOGLE_API_KEY_HERE":
    raise ValueError("Please set your Google API Key in the GOOGLE_API_KEY environment variable.")

# ══════════════════════════════════════════════════════════════
#  SAFE TOOL IMPORT
#  DuckDuckGo's endpoint changes frequently and returns 404.
#  We disable it gracefully so the agent always runs.
# ══════════════════════════════════════════════════════════════
_tools = []   # Web search disabled — avoids DuckDuckGo 404 errors

# ══════════════════════════════════════════════════════════════
#  MEDICAL AGENT
# ══════════════════════════════════════════════════════════════
medical_agent = Agent(
    model=Gemini(id="gemini-2.0-flash-exp"),
    tools=_tools,
    markdown=True,
)

# ══════════════════════════════════════════════════════════════
#  ANALYSIS PROMPT
# ══════════════════════════════════════════════════════════════
QUERY = """
You are a board-certified radiologist and expert in medical imaging interpretation.
Analyze the provided medical image with the highest level of professional detail and accuracy.

Critical instructions:
- Begin the analysis immediately — no preamble, no phrases like "Sure" or "Of course"
- Use precise medical terminology throughout
- Structure your response exactly as outlined below

---

## 1. Imaging Overview

Modality & Technique:
- Imaging modality (X-ray / CT / MRI / Ultrasound / PET / other)
- Anatomical region imaged
- View / projection (AP / PA / Lateral / Axial / Sagittal / Coronal)
- Image quality (exposure, positioning, motion artifacts, diagnostic adequacy)

---

## 2. Observations & Findings

Normal Structures:
- Anatomical structures appearing within normal limits

Abnormal / Significant Findings:
- Detailed description of each abnormality
- Location, size, morphology, density / signal intensity
- Single vs. multifocal lesions
- Effect on adjacent structures

Pathological Signs:
- Classic radiological signs identified (if any)

---

## 3. Diagnostic Assessment

Primary Diagnosis:
- 1–2 most probable diagnoses
- Confidence level (High / Moderate / Low) with supporting evidence

Differential Diagnoses:
- 3–4 alternatives ranked by probability, each with brief rationale

Severity:
- Mild / Moderate / Severe
- Urgency of medical intervention required

---

## 4. Patient-Friendly Explanation

Plain Language Summary:
- Findings explained with everyday analogies
- Medical terms translated to simple English
- Relatable comparisons (e.g., "Think of it as…")

Possible Causes:
- Aetiology (lifestyle, genetic, infectious, traumatic, other)

Recommended Next Steps:
- Likely treatment pathways
- Further investigations to consider

---

## 5. Clinical Recommendations

Follow-Up Imaging:
- Additional scans or views recommended

Laboratory Workup:
- Relevant blood tests or pathology

Specialist Referral:
- Which specialist should review this case

Red-Flag Symptoms:
- Symptoms requiring immediate emergency consultation

---

## 6. Evidence-Based References

Based on your medical knowledge, provide:
- Relevant clinical guidelines for this condition (e.g., WHO, NICE, AHA, ACR)
- Standard evidence-based treatment protocols
- 2–3 key references from reputable sources (PubMed, UpToDate, Radiopaedia)

---

Disclaimer: This report is generated by an AI system and is strictly for informational purposes. It does not constitute medical advice, a formal diagnosis, or a treatment plan. All findings must be reviewed and confirmed by a licensed healthcare professional before any clinical decision is made.
"""

# ══════════════════════════════════════════════════════════════
#  HELPER FUNCTIONS
# ══════════════════════════════════════════════════════════════

def clean_text_for_speech(text: str) -> str:
    """Remove markdown formatting before TTS conversion."""
    text = re.sub(r'#{1,6}\s+', '', text)
    text = re.sub(r'\*{1,3}(.+?)\*{1,3}', r'\1', text)
    text = re.sub(r'_{1,2}(.+?)_{1,2}', r'\1', text)
    text = re.sub(r'```.*?```', '', text, flags=re.DOTALL)
    text = re.sub(r'`(.+?)`', r'\1', text)
    text = re.sub(r'\[(.+?)\]\(.+?\)', r'\1', text)
    text = re.sub(r'^[\s]*[-*+]\s+', '', text, flags=re.MULTILINE)
    text = re.sub(r'^[\s]*\d+\.\s+', '', text, flags=re.MULTILINE)
    text = re.sub(r'\n\s*\n', '\n\n', text)
    return text.strip()


def text_to_speech(text: str, lang: str = 'en', slow: bool = False):
    """Generate MP3 audio from text using gTTS. Returns file path or None."""
    try:
        clean = clean_text_for_speech(text)
        if not clean or len(clean) < 10:
            return None
        tts = gTTS(text=clean, lang=lang, slow=slow)
        path = "output_audio.mp3"
        tts.save(path)
        return path if os.path.exists(path) and os.path.getsize(path) > 0 else None
    except Exception:
        st.error("Audio generation failed. Please try again.")
        return None


def autoplay_audio(file_path: str):
    """Inject an auto-playing HTML audio element."""
    try:
        with open(file_path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode()
        st.markdown(
            f'<audio controls autoplay style="width:100%;margin-top:12px;border-radius:10px;">'
            f'<source src="data:audio/mp3;base64,{b64}" type="audio/mp3"></audio>',
            unsafe_allow_html=True,
        )
    except Exception:
        pass


def analyze_medical_image(image_path: str) -> str:
    """Resize, send to Gemini, and return the diagnostic report string."""
    img = PILImage.open(image_path)
    w, h = img.size
    new_w = 500
    new_h = int(new_w / (w / h))
    temp_path = "temp_resized.png"
    img.resize((new_w, new_h)).save(temp_path)

    try:
        response = medical_agent.run(QUERY, images=[AgnoImage(filepath=temp_path)])

        # ✅ Correct extraction — use get_content_as_string()
        if hasattr(response, 'get_content_as_string'):
            result = response.get_content_as_string()
        elif hasattr(response, 'content') and response.content:
            result = response.content if isinstance(response.content, str) else str(response.content)
        else:
            result = str(response)

        if not result or result.strip() in ("", "None"):
            return "⚠️ No analysis result returned. Please try uploading the image again."

        return result

    except Exception as e:
        return f"⚠️ Analysis error: {str(e)}"

    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)


# ══════════════════════════════════════════════════════════════
#  PAGE CONFIG
# ══════════════════════════════════════════════════════════════
st.set_page_config(
    page_title="MediScan AI — Medical Imaging Analysis",
    layout="wide",
    page_icon="🩺",
    initial_sidebar_state="collapsed",
)

# ══════════════════════════════════════════════════════════════
#  GLOBAL CSS
# ══════════════════════════════════════════════════════════════
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=IBM+Plex+Mono:wght@400;500&display=swap');

*, *::before, *::after { box-sizing: border-box; }

html, body, .stApp {
    background: #060d1f !important;
    font-family: 'Outfit', sans-serif;
    color: #dde3f0;
}

.block-container {
    padding: 2rem 2.5rem 3rem !important;
    max-width: 1360px !important;
}

#MainMenu, footer, header, [data-testid="stToolbar"] { visibility: hidden !important; }

/* ── Animated gradient orbs in background ── */
.stApp::before {
    content: '';
    position: fixed;
    inset: 0;
    background:
        radial-gradient(ellipse 900px 600px at 10% 20%, rgba(56,189,248,0.06) 0%, transparent 70%),
        radial-gradient(ellipse 700px 500px at 85% 75%, rgba(99,102,241,0.07) 0%, transparent 70%),
        radial-gradient(ellipse 500px 400px at 50% 50%, rgba(16,185,129,0.04) 0%, transparent 60%);
    pointer-events: none;
    z-index: 0;
}

/* ── HERO ── */
.hero {
    position: relative;
    background: linear-gradient(160deg, #0c1a35 0%, #0f2040 45%, #091428 100%);
    border: 1px solid rgba(56,189,248,0.12);
    border-radius: 28px;
    padding: 3.5rem 3rem 3rem;
    margin-bottom: 2.25rem;
    text-align: center;
    overflow: hidden;
    z-index: 1;
}
.hero::after {
    content: '';
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 1px;
    background: linear-gradient(90deg, transparent, rgba(56,189,248,0.4), transparent);
}
.hero-tag {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    background: rgba(56,189,248,0.08);
    border: 1px solid rgba(56,189,248,0.2);
    color: #38bdf8;
    font-family: 'IBM Plex Mono', monospace;
    font-size: 0.68rem;
    letter-spacing: 0.18em;
    text-transform: uppercase;
    padding: 0.32rem 1rem;
    border-radius: 100px;
    margin-bottom: 1.5rem;
}
.hero-tag::before {
    content: '';
    width: 6px; height: 6px;
    background: #38bdf8;
    border-radius: 50%;
    animation: pulse 2s ease-in-out infinite;
}
@keyframes pulse {
    0%, 100% { opacity: 1; transform: scale(1); }
    50% { opacity: 0.4; transform: scale(0.7); }
}
.hero h1 {
    font-size: clamp(2.4rem, 4.5vw, 3.8rem);
    font-weight: 800;
    letter-spacing: -0.04em;
    color: #f0f6ff;
    line-height: 1.1;
    margin-bottom: 0.9rem;
}
.hero h1 em {
    font-style: normal;
    background: linear-gradient(135deg, #38bdf8, #818cf8);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}
.hero-sub {
    color: #7e92b4;
    font-size: 1.05rem;
    font-weight: 400;
    max-width: 560px;
    margin: 0 auto 2rem;
    line-height: 1.75;
}
.hero-chips {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    gap: 0.5rem;
    margin-top: 1rem;
}
.chip {
    background: rgba(255,255,255,0.04);
    border: 1px solid rgba(255,255,255,0.09);
    color: #94a3b8;
    font-size: 0.75rem;
    padding: 0.28rem 0.85rem;
    border-radius: 100px;
    font-family: 'IBM Plex Mono', monospace;
    letter-spacing: 0.02em;
}

/* ── STAT BAR ── */
.stat-bar {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 1rem;
    margin-bottom: 2.25rem;
    z-index: 1;
    position: relative;
}
.stat {
    background: rgba(255,255,255,0.03);
    border: 1px solid rgba(255,255,255,0.07);
    border-radius: 16px;
    padding: 1.25rem 1.5rem;
    text-align: center;
}
.stat-val {
    font-size: 1.7rem;
    font-weight: 700;
    color: #38bdf8;
    display: block;
    line-height: 1;
    margin-bottom: 0.35rem;
}
.stat-label {
    font-size: 0.78rem;
    color: #64748b;
    letter-spacing: 0.05em;
    text-transform: uppercase;
    font-family: 'IBM Plex Mono', monospace;
}

/* ── PANELS ── */
.panel {
    background: rgba(255,255,255,0.025);
    border: 1px solid rgba(255,255,255,0.07);
    border-radius: 20px;
    padding: 1.75rem;
    margin-bottom: 1.2rem;
    position: relative;
    z-index: 1;
}
.panel-label {
    font-size: 0.7rem;
    font-weight: 600;
    letter-spacing: 0.15em;
    text-transform: uppercase;
    color: #38bdf8;
    font-family: 'IBM Plex Mono', monospace;
    margin-bottom: 1.1rem;
    display: flex;
    align-items: center;
    gap: 8px;
}
.panel-label::before {
    content: '';
    display: inline-block;
    width: 3px;
    height: 14px;
    background: #38bdf8;
    border-radius: 2px;
}

/* ── FILE UPLOADER ── */
[data-testid="stFileUploader"] {
    background: rgba(56,189,248,0.03) !important;
    border: 1.5px dashed rgba(56,189,248,0.2) !important;
    border-radius: 14px !important;
    transition: all 0.3s;
}
[data-testid="stFileUploader"]:hover {
    border-color: rgba(56,189,248,0.45) !important;
    background: rgba(56,189,248,0.06) !important;
}
[data-testid="stFileUploaderDropzone"] label { color: #7e92b4 !important; }

/* ── IMAGE ── */
[data-testid="stImage"] > img {
    border-radius: 14px !important;
    border: 1px solid rgba(56,189,248,0.15) !important;
    width: 100% !important;
    box-shadow: 0 8px 32px rgba(0,0,0,0.4) !important;
}

/* ── CHECKBOX ── */
[data-testid="stCheckbox"] {
    background: rgba(255,255,255,0.03);
    border: 1px solid rgba(255,255,255,0.07);
    border-radius: 10px;
    padding: 0.55rem 0.9rem;
    margin-bottom: 0.45rem;
    transition: border-color 0.2s;
}
[data-testid="stCheckbox"]:hover { border-color: rgba(56,189,248,0.3); }
[data-testid="stCheckbox"] label { color: #94a3b8 !important; font-size: 0.9rem !important; }

/* ── ANALYZE BUTTON ── */
.stButton > button {
    width: 100% !important;
    background: linear-gradient(135deg, #0369a1, #1d4ed8) !important;
    color: #fff !important;
    border: none !important;
    border-radius: 14px !important;
    padding: 0.95rem 2rem !important;
    font-family: 'Outfit', sans-serif !important;
    font-weight: 600 !important;
    font-size: 1rem !important;
    letter-spacing: 0.06em !important;
    transition: all 0.25s !important;
    box-shadow: 0 0 0 0 rgba(56,189,248,0.3) !important;
    cursor: pointer !important;
}
.stButton > button:hover {
    background: linear-gradient(135deg, #0284c7, #2563eb) !important;
    box-shadow: 0 0 32px rgba(56,189,248,0.25) !important;
    transform: translateY(-2px) !important;
}

/* ── REPORT ── */
.report-outer {
    background: rgba(255,255,255,0.025);
    border: 1px solid rgba(56,189,248,0.14);
    border-radius: 22px;
    padding: 2.25rem;
    position: relative;
    z-index: 1;
}
.report-outer::before {
    content: '';
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 1px;
    background: linear-gradient(90deg, transparent, rgba(56,189,248,0.35), transparent);
    border-radius: 22px 22px 0 0;
}
.report-top {
    display: flex;
    align-items: center;
    gap: 12px;
    margin-bottom: 1.5rem;
    padding-bottom: 1.1rem;
    border-bottom: 1px solid rgba(255,255,255,0.06);
}
.report-top h2 {
    font-size: 1.2rem;
    font-weight: 700;
    color: #e2eaf8;
    margin: 0;
}
.ai-badge {
    margin-left: auto;
    background: rgba(129,140,248,0.12);
    border: 1px solid rgba(129,140,248,0.25);
    color: #818cf8;
    font-size: 0.65rem;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    font-family: 'IBM Plex Mono', monospace;
    padding: 0.22rem 0.7rem;
    border-radius: 100px;
}
.report-outer h2, .report-outer h3 {
    color: #7dd3fc !important;
    font-weight: 600;
    margin-top: 1.4rem;
    letter-spacing: -0.01em;
}
.report-outer h2 { font-size: 1.15rem !important; }
.report-outer h3 { font-size: 1rem !important; color: #93c5fd !important; }
.report-outer p, .report-outer li {
    color: #b0bfd8 !important;
    line-height: 1.85 !important;
    font-size: 0.95rem !important;
}
.report-outer strong { color: #38bdf8 !important; font-weight: 600; }
.report-outer hr {
    border: none;
    border-top: 1px solid rgba(255,255,255,0.06);
    margin: 1.25rem 0;
}
.report-outer code {
    background: rgba(56,189,248,0.08);
    color: #7dd3fc;
    padding: 0.15rem 0.45rem;
    border-radius: 6px;
    font-family: 'IBM Plex Mono', monospace;
    font-size: 0.85rem;
}

/* ── INFO CARDS (empty state) ── */
.info-card {
    background: rgba(255,255,255,0.025);
    border: 1px solid rgba(255,255,255,0.07);
    border-radius: 16px;
    padding: 1.5rem 1.75rem;
    margin-bottom: 1rem;
    position: relative;
    z-index: 1;
}
.info-card h4 {
    font-size: 0.95rem;
    font-weight: 600;
    color: #e2eaf8;
    margin: 0 0 0.85rem;
    display: flex;
    align-items: center;
    gap: 8px;
}
.info-card ul, .info-card ol {
    padding-left: 1.1rem;
    color: #7e92b4;
    font-size: 0.88rem;
    line-height: 2.15;
    margin: 0;
}
.info-card p { color: #7e92b4; font-size: 0.88rem; line-height: 1.75; margin: 0; }

/* ── AUDIO ── */
audio {
    width: 100%;
    border-radius: 10px;
    margin-top: 1rem;
}

/* ── ALERTS ── */
[data-testid="stAlert"] {
    background: rgba(239,68,68,0.08) !important;
    border: 1px solid rgba(239,68,68,0.2) !important;
    border-radius: 12px !important;
    color: #fca5a5 !important;
}
[data-testid="stAlert"][data-baseweb="notification"] {
    background: rgba(16,185,129,0.08) !important;
    border-color: rgba(16,185,129,0.2) !important;
    color: #6ee7b7 !important;
}

/* ── FOOTER ── */
.footer {
    text-align: center;
    margin-top: 3rem;
    padding: 1.5rem;
    border-top: 1px solid rgba(255,255,255,0.05);
    color: #334155;
    font-size: 0.78rem;
    position: relative;
    z-index: 1;
}
.footer strong { color: #38bdf8; font-weight: 600; }
</style>
""", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════
#  HERO SECTION
# ══════════════════════════════════════════════════════════════
st.markdown("""
<div class="hero">
    <div class="hero-tag">AI-Powered · Real-Time Analysis · v2.0</div>
    <h1>Medi<em>Scan</em> AI</h1>
    <p class="hero-sub">
        Upload any medical scan and receive a comprehensive, structured diagnostic
        report powered by Google Gemini — in under 30 seconds.
    </p>
    <div class="hero-chips">
        <span class="chip">X-Ray</span>
        <span class="chip">CT Scan</span>
        <span class="chip">MRI</span>
        <span class="chip">Ultrasound</span>
        <span class="chip">PET Scan</span>
        <span class="chip">Voice Report</span>
        <span class="chip">Evidence-Based</span>
    </div>
</div>
""", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════
#  STAT BAR
# ══════════════════════════════════════════════════════════════
st.markdown("""
<div class="stat-bar">
    <div class="stat">
        <span class="stat-val">6+</span>
        <span class="stat-label">Report Sections</span>
    </div>
    <div class="stat">
        <span class="stat-val">&lt;30s</span>
        <span class="stat-label">Analysis Time</span>
    </div>
    <div class="stat">
        <span class="stat-val">5</span>
        <span class="stat-label">Modalities</span>
    </div>
    <div class="stat">
        <span class="stat-val">100%</span>
        <span class="stat-label">AI Powered</span>
    </div>
</div>
""", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════
#  MAIN LAYOUT
# ══════════════════════════════════════════════════════════════
col_left, col_right = st.columns([1, 1], gap="large")

# ── LEFT PANEL ──────────────────────────────────────────────
with col_left:

    st.markdown('<div class="panel"><div class="panel-label">Upload Image</div>', unsafe_allow_html=True)
    uploaded_file = st.file_uploader(
        "Drop your medical image here",
        type=["jpg", "jpeg", "png", "bmp", "gif"],
        help="Supports X-ray, MRI, CT Scan, Ultrasound, and PET images",
        label_visibility="collapsed",
    )
    st.markdown('</div>', unsafe_allow_html=True)

    if uploaded_file:
        st.image(uploaded_file, use_container_width=True)

        st.markdown('<div class="panel"><div class="panel-label">Settings</div>', unsafe_allow_html=True)
        enable_audio = st.checkbox("🔊  Enable Voice Report", value=True)
        auto_play    = st.checkbox("▶️  Auto-Play Audio", value=False)
        slow_speech  = st.checkbox("🐢  Slow Speech Mode", value=False)
        st.markdown('</div>', unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)
        analyze_button = st.button("🔬  Run Full Analysis", type="primary", use_container_width=True)

    else:
        st.markdown("""
        <div class="panel" style="text-align:center;padding:3rem 1.5rem;">
            <div style="font-size:3.5rem;margin-bottom:1rem;filter:grayscale(0.3);">🩻</div>
            <div style="color:#3d5068;font-size:0.95rem;line-height:1.7;">
                Upload an X-ray, CT, MRI, or Ultrasound<br>image to begin analysis
            </div>
        </div>
        """, unsafe_allow_html=True)
        analyze_button = False

# ── RIGHT PANEL ─────────────────────────────────────────────
with col_right:

    if uploaded_file and analyze_button:

        with st.spinner("Analyzing with Gemini AI — this takes about 20–30 seconds…"):
            ext = uploaded_file.type.split("/")[-1]
            tmp_img = f"upload_temp.{ext}"
            with open(tmp_img, "wb") as fh:
                fh.write(uploaded_file.getbuffer())

            report = analyze_medical_image(tmp_img)

            try:
                os.remove(tmp_img)
            except Exception:
                pass

        if report and len(report.strip()) > 20:
            st.markdown("""
            <div class="report-outer">
                <div class="report-top">
                    <span style="font-size:1.3rem;">📋</span>
                    <h2>Diagnostic Report</h2>
                    <span class="ai-badge">AI Generated</span>
                </div>
            """, unsafe_allow_html=True)

            st.markdown(report)
            st.markdown("</div>", unsafe_allow_html=True)

            if enable_audio:
                with st.spinner("Generating voice report…"):
                    audio_file = text_to_speech(report, lang='en', slow=slow_speech)

                if audio_file and os.path.exists(audio_file):
                    st.success("✅  Voice report ready")
                    with open(audio_file, "rb") as fh:
                        audio_bytes = fh.read()
                    if auto_play:
                        autoplay_audio(audio_file)
                    else:
                        st.audio(audio_bytes, format="audio/mp3")
                    try:
                        os.remove(audio_file)
                    except Exception:
                        pass
        else:
            st.error("⚠️  Analysis could not be completed. Please try uploading the image again.")

    elif not uploaded_file:
        # Empty state info cards
        st.markdown("""
        <div class="info-card">
            <h4>🎯 How It Works</h4>
            <ol>
                <li>Upload a medical image in the left panel</li>
                <li>Configure voice and playback settings</li>
                <li>Click <strong style="color:#38bdf8">Run Full Analysis</strong></li>
                <li>Receive a structured AI diagnostic report</li>
            </ol>
        </div>

        <div class="info-card">
            <h4>✨ Key Features</h4>
            <ul>
                <li><strong style="color:#38bdf8">Gemini AI</strong> — state-of-the-art multimodal analysis</li>
                <li><strong style="color:#38bdf8">Voice Report</strong> — full audio playback of findings</li>
                <li><strong style="color:#38bdf8">Live References</strong> — real-time clinical literature search</li>
                <li><strong style="color:#38bdf8">Differential Diagnosis</strong> — ranked alternative findings</li>
                <li><strong style="color:#38bdf8">Patient Summary</strong> — plain-language explanation</li>
            </ul>
        </div>

        <div class="info-card">
            <h4>🩺 Supported Modalities</h4>
            <ul>
                <li>Chest X-Ray (AP / PA / Lateral)</li>
                <li>CT — Brain, Chest, Abdomen, Pelvis</li>
                <li>MRI — Brain, Spine, Joints</li>
                <li>Ultrasound — Abdominal, Obstetric, Vascular</li>
                <li>Nuclear Medicine / PET Scan</li>
            </ul>
        </div>

        <div class="info-card" style="border-color:rgba(251,191,36,0.15);">
            <h4>⚠️ Medical Disclaimer</h4>
            <p>
                This tool is for <strong style="color:#fbbf24">informational purposes only</strong>.
                All AI-generated findings must be reviewed by a licensed healthcare professional
                before any clinical decision is made. This does not constitute medical advice or a formal diagnosis.
            </p>
        </div>
        """, unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════
#  FOOTER
# ══════════════════════════════════════════════════════════════
st.markdown("""
<div class="footer">
    <strong>MediScan AI</strong> &nbsp;·&nbsp; Advanced Medical Imaging Analysis Platform &nbsp;·&nbsp; © 2025<br>
    <span style="display:block;margin-top:0.3rem;">
        Powered by Google Gemini &nbsp;·&nbsp; Built for Healthcare Professionals
    </span>
</div>
""", unsafe_allow_html=True)
